# Generated by Django 2.0.2 on 2019-04-29 20:03

import Datos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=Datos.models.image_Datos4),
        ),
        migrations.AlterField(
            model_name='datos',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=Datos.models.image_Datos1),
        ),
        migrations.AlterField(
            model_name='datos',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=Datos.models.image_Datos2),
        ),
        migrations.AlterField(
            model_name='datos',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=Datos.models.image_Datos3),
        ),
    ]
