# Generated by Django 2.0.2 on 2019-04-19 02:13

import Pag.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('headers', models.CharField(blank=True, max_length=240, null=True, verbose_name='Encabezado')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(upload_to=Pag.models.image_Pag)),
                ('state', models.CharField(default='Activo', max_length=240)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
                'ordering': ['name'],
            },
        ),
    ]
